#!/bin/bash

RED=$'\033[1;31m'
GREEN=$'\033[1;32m'
YELLOW=$'\033[1;33m'
BLUE=$'\033[1;34m'
PURPLE=$'\033[1;35m'
GRAY=$'\033[1;30m'
CYAN=$'\033[1;36m'
WHITE=$'\033[1;37m'
NC=$'\033[0m'

if [ -f "/data/data/com.termux/files/usr/bin/tmxlogin" ]; then

    echo "${GREEN} Available ${NC}"

    if ! rm -f "/data/data/com.termux/files/usr/bin/tmxlogin"; then
        echo "${RED}File removal problem [/data/data/com.termux/files/usr/bin/tmxlogin]${NC}"
    else
        echo "${GREEN}File removal Done !${NC}"
    fi

    echo ""    
    echo "${RED}Manualy remove the 'login' word from the /usr/etc/bash.bashrc file ${NC}"

    echo "${GREEN}All Done ${NC}"
    echo "${GREEN}Join Our Telegram Channel${NC}"
    sleep 1
    xdg-open https://t.me/cyber_man_root

else
    echo "${RED}File not found${NC}"
fi

